[package]
distribution = "2201.13.0"
org = "ballerinax"
name = "github"
version = "6.0.0"
authors = ["Ballerina"]
export = ["github"]
keywords = ["Type/Connector", "Cost/Freemium", "Vendor/GitHub", "Area/Developer Tools", "IT Operations/Source Control"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-github"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = false
